language: rust
cache: cargo
rust:
- nightly
- beta
- stable
- 1.20.0
script:
- cargo test
- cargo test --features "verbose-errors little-skeptic"
- cargo test --features no-default-features
env:
  global:
  - secure: Z0JCbroitF6pKdImGLcar9UcXDFUoggvEwYsksoGX16/28iBXLmBX6DDWN1brVdasx/i5M5aEy8xbzcV680+HEbbUgz5uLAMp3xQFzu5FJ276PM9ZFZZgb02EJuYz9THfrC9ajlc+CirYF91i/yMZbpBGajmAzp61puRph/CgI8=
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/ee4400ef3d920e51415e
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
